# Generated by Django 5.1.1 on 2024-09-17 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('goals', models.TextField(verbose_name='Doelen van de dag/week')),
                ('time_registration', models.TextField(verbose_name='Tijdregistratie')),
                ('tasks_completed', models.TextField(verbose_name='Uitgevoerde taken')),
                ('problems_challenges', models.TextField(verbose_name='Problemen en uitdagingen')),
                ('solutions_learnings', models.TextField(verbose_name='Oplossingen en leerpunten')),
                ('feedback_reflection', models.TextField(verbose_name='Feedback of reflectie')),
                ('todo_next', models.TextField(verbose_name='To-do voor de volgende dag/week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Logbook Entries',
                'ordering': ['-date'],
            },
        ),
    ]
